### ISSUE TITLE
App crashing after selection 2019 season

### ISSUE THREAD

**Issue by traschke** [leonardoxh/race-control-tv#127]
The app is crashing for me when selecting the *2019* season in the *Archive* row on the main screen. Other seasons seem to work fine so far. I added some information below. If you need further information or help I'd be pleased to help.

### Steps to repruduce the issue

Start the app and select the 2019 season from the main screen in the archive row.

### Device Information

| Property | Value |
| -- | -- |
| Device | Xiaomi MiBox S (MDZ-22-AB) |
| OS-Build | PI.3934 release-keys |
| Android Version | 9 |
| Kernel Version | 4.9.113 |

### Logcat

```log
--------- beginning of main
04-19 22:42:28.202  8292  8292 W b.leonardoxh.f: Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
04-19 22:42:28.215  8292  8292 E b.leonardoxh.f: Not starting debugger since process cannot load the jdwp agent.
04-19 22:42:28.440  8292  8292 D LoadingFragment: onCreateView
04-19 22:42:28.455  8292  8292 D OpenGLRenderer: Skia GL Pipeline
04-19 22:42:28.509  8292  8311 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
04-19 22:42:28.509  8292  8311 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
04-19 22:42:28.509  8292  8311 I OpenGLRenderer: Initialized EGL, version 1.4
04-19 22:42:28.510  8292  8311 D OpenGLRenderer: Swap behavior 1
04-19 22:42:28.710  8292  8292 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@1c736e9
04-19 22:42:28.804  8292  8292 D NetworkSecurityConfig: No Network Security Config specified, using platform default
04-19 22:42:29.316  8292  8292 D HomeActivity: onStart
04-19 22:42:29.316  8292  8292 D LoadingFragment: onCreateView
04-19 22:42:29.321  8292  8292 D Fetching new data: Lifecycle state is STARTED
04-19 22:42:29.323  8292  8307 D f       : loadSeason 2022
04-19 22:42:29.699  8292  8307 D k       : Fetched season Archive(year=2022)
04-19 22:42:29.762  8292  8307 D b       : loadSessionsWithImages
04-19 22:42:29.994  8292  8307 D k       : Fetched broadcasted sessions for event 1500000149
04-19 22:42:29.995  8292  8307 D k       : Unable to parse date Text '' could not be parsed at index 0
04-19 22:42:30.020  8292  8307 I chatty  : uid=10118(com.github.leonardoxh.f1) DefaultDispatch identical 92 lines
04-19 22:42:30.020  8292  8307 D k       : Unable to parse date Text '' could not be parsed at index 0
04-19 22:42:30.192  8292  8307 D k       : Fetched broadcasted sessions for event 1500000148
04-19 22:42:30.193  8292  8307 D k       : Unable to parse date Text '' could not be parsed at index 0
04-19 22:42:30.202  8292  8307 I chatty  : uid=10118(com.github.leonardoxh.f1) DefaultDispatch identical 20 lines
04-19 22:42:30.203  8292  8307 D k       : Unable to parse date Text '' could not be parsed at index 0
04-19 22:42:30.324  8292  8307 D k       : Fetched broadcasted sessions for event 1500000157
04-19 22:42:30.325  8292  8307 D k       : Unable to parse date Text '' could not be parsed at index 0
04-19 22:42:30.341  8292  8307 I chatty  : uid=10118(com.github.leonardoxh.f1) DefaultDispatch identical 42 lines
04-19 22:42:30.341  8292  8307 D k       : Unable to parse date Text '' could not be parsed at index 0
04-19 22:42:30.551  8292  8307 D k       : Fetched broadcasted sessions for event 1500000150
04-19 22:42:30.552  8292  8307 D k       : Unable to parse date Text '' could not be parsed at index 0
04-19 22:42:30.574  8292  8307 I chatty  : uid=10118(com.github.leonardoxh.f1) DefaultDispatch identical 74 lines
04-19 22:42:30.574  8292  8307 D k       : Unable to parse date Text '' could not be parsed at index 0
04-19 22:42:30.721  8292  8307 D k       : Fetched broadcasted sessions for event 1500000158
04-19 22:42:30.722  8292  8307 D k       : Unable to parse date Text '' could not be parsed at index 0
04-19 22:42:30.736  8292  8307 I chatty  : uid=10118(com.github.leonardoxh.f1) DefaultDispatch identical 54 lines
04-19 22:42:30.736  8292  8307 D k       : Unable to parse date Text '' could not be parsed at index 0
04-19 22:42:30.789  8292  8292 D f       : listSeasons
04-19 22:42:30.860  8292  8292 D f       : Season changed
04-19 22:42:30.870  8292  8292 D f       : Events changed
04-19 22:42:30.921  8292  8292 D f       : Sessions changed
04-19 22:42:30.935  8292  8292 D f       : VM sessions changed
04-19 22:42:30.936  8292  8292 D f       : Sessions changed
04-19 22:42:30.946  8292  8292 D f       : VM sessions changed
04-19 22:42:30.947  8292  8292 D f       : Sessions changed
04-19 22:42:30.950  8292  8292 D f       : VM sessions changed
04-19 22:42:30.950  8292  8292 D f       : Sessions changed
04-19 22:42:30.954  8292  8292 D f       : VM sessions changed
04-19 22:42:30.955  8292  8292 D f       : Sessions changed
04-19 22:42:30.955  8292  8292 D f       : VM sessions changed
04-19 22:42:30.955  8292  8292 D f       : Sessions changed
04-19 22:42:30.955  8292  8292 D f       : VM sessions changed
04-19 22:42:30.956  8292  8292 D f       : Sessions changed
04-19 22:42:30.956  8292  8292 D f       : VM sessions changed
04-19 22:42:30.957  8292  8292 D f       : Sessions changed
04-19 22:42:30.957  8292  8292 D f       : VM sessions changed
04-19 22:42:30.957  8292  8292 D f       : Sessions changed
04-19 22:42:30.957  8292  8292 D f       : VM sessions changed
04-19 22:42:30.959  8292  8292 D f       : Sessions changed
04-19 22:42:30.959  8292  8292 D f       : VM sessions changed
04-19 22:42:30.960  8292  8292 D f       : Sessions changed
04-19 22:42:30.960  8292  8292 D f       : VM sessions changed
04-19 22:42:30.961  8292  8292 D f       : Sessions changed
04-19 22:42:30.961  8292  8292 D f       : VM sessions changed
04-19 22:42:30.961  8292  8292 D f       : Sessions changed
04-19 22:42:30.961  8292  8292 D f       : VM sessions changed
04-19 22:42:30.962  8292  8292 D f       : Sessions changed
04-19 22:42:30.962  8292  8292 D f       : VM sessions changed
04-19 22:42:30.962  8292  8292 D f       : Sessions changed
04-19 22:42:30.963  8292  8292 D f       : VM sessions changed
04-19 22:42:30.963  8292  8292 D f       : Sessions changed
04-19 22:42:30.964  8292  8292 D f       : VM sessions changed
04-19 22:42:30.964  8292  8292 D f       : Sessions changed
04-19 22:42:30.966  8292  8292 D f       : VM sessions changed
04-19 22:42:30.966  8292  8292 D f       : VM events changed
04-19 22:42:30.967  8292  8292 D f       : VM season changed
04-19 22:42:31.014  8292  8292 W Glide   : Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
04-19 22:42:31.094  8292  8292 D g       : onCreateViewHolder
04-19 22:42:31.110  8292  8292 I chatty  : uid=10118(com.github.leonardoxh.f1) identical 4 lines
04-19 22:42:31.112  8292  8292 D g       : onCreateViewHolder
04-19 22:42:44.588  8292  8292 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@bc8877c
04-19 22:42:44.613  8292  8292 D LoadingFragment: onCreateView
04-19 22:42:44.620  8292  8292 D Fetching new data: Lifecycle state is STARTED
04-19 22:42:44.621  8292  8307 D f       : loadSeason 2019
04-19 22:42:44.633  8292  8292 D f       : Season changed
--------- beginning of crash
04-19 22:42:44.717  8292  8292 E AndroidRuntime: FATAL EXCEPTION: main
04-19 22:42:44.717  8292  8292 E AndroidRuntime: Process: com.github.leonardoxh.f1, PID: 8292
04-19 22:42:44.717  8292  8292 E AndroidRuntime: d.f.a.n: Required value 'emfAttributes' missing at $.resultObj.containers[9].metadata
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at d.f.a.y.b.e(Unknown Source:43)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at fr.groggy.racecontrol.tv.f1tv.F1TvSeasonMetadataJsonAdapter.a(:1)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at d.f.a.y.a.a(Unknown Source:15)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at fr.groggy.racecontrol.tv.f1tv.F1TvSeasonResultContainerJsonAdapter.a(:1)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at d.f.a.y.a.a(Unknown Source:15)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at d.f.a.h.c(Unknown Source:15)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at d.f.a.h.a(Unknown Source:0)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at d.f.a.y.a.a(Unknown Source:15)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at fr.groggy.racecontrol.tv.f1tv.F1TvSeasonResultJsonAdapter.a(:1)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at d.f.a.y.a.a(Unknown Source:15)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at fr.groggy.racecontrol.tv.f1tv.F1TvSeasonResponseJsonAdapter.a(:1)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at d.f.a.y.a.a(Unknown Source:15)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at f.a.a.a.p.a.c.k(:7)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at d.d.a.b.a.E1(Unknown Source:6)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at d.d.a.b.a.X1(:1)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at f.a.a.a.p.a.d.a(:4)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at f.a.a.a.m.k.a(:2)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at f.a.a.a.m.k$a.o(Unknown Source:12)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at h.m.k.a.a.m(:2)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at i.a.x1.i0(Unknown Source:41)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at i.a.c.m(:2)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at h.m.k.a.a.m(:2)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at i.a.i0.run(Unknown Source:86)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at i.a.e2.a.y(Unknown Source:0)
04-19 22:42:44.717  8292  8292 E AndroidRuntime: 	at i.a.e2.a$a.run(:5)
04-19 22:42:44.736  8292  8292 I Process : Sending signal. PID: 8292 SIG: 9
```

**Comment by leonardoxh** [comment]
I see.

Looks like it is something they changed in their api, will take a look at it soon as the DRM issues are solved.
